title:            '米楽高'
description:      '一个程序员'
url:              'http://notes.milegao.com'
signoff:          '陈钧'
disqus_shortname: 'milegao'
facebook_appid:   '1749201265341783'
google_analytics: ''
timezone:         Asia/Tokyo
highlighter:      pygments
future:           true
repository_url:   https://github.com/garycruise/garycruise.github.io.git

links:
  - name:         Blog
    url:          /
  - name:         RSS
    url:          /feed.xml
  - name:         About
    url:          /about.html

permalink:        /:title.html
markdown:         kramdown
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

sass:
  style: compressed