title:            '米楽高'
description:      '一个程序员'
url:              'https://milegao.com'
signoff:          '陈钧'
disqus_shortname: milegao
facebook_appid:   1749201265341783
timezone:         Asia/Tokyo
highlighter:      pygments
future:           true
repository_url:   https://github.com/garycruise/garycruise.github.io

links:
  - name:         Blog
    url:          /
  - name:         RSS
    url:          /feed.xml
  - name:         About
    url:          /about/

permalink:        pretty
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

sass:
  style: compressed